name: youtube_music_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  # 플랫폼별 오디오 지원
  media_kit: ^1.1.11
  # 안드로이드 알림 아이콘 지원
  flutter_local_notifications: ^19.2.0
  # 유튜브 API 지원
  youtube_explode_dart: ^2.4.0
  google_fonts: ^6.2.1
  # 경로 관리
  path_provider: ^2.1.2
  # UUID 생성
  uuid: ^4.3.3
  # HTTP 클라이언트
  dio: ^5.4.3+1
  # 파일 선택 다이얼로그
  file_picker: ^10.1.9
  media_kit_libs_android_audio: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
